### ISSUE TITLE
There was an error loading the preference bundle for notiping

### ISSUE THREAD

**Issue by brandonheley** [ItHertzSoGood/notiping#1]
**Tell me about your setup:**  
1.) What version of iOS are you on, and what device?
13.5
**How can I recreate the issue?**
1.) i got the repo 
2.) added notiping and resprung
3.) the error appeared in settings 
...

**What do you expect, and what is happening instead?**
Not letting me see settings of the tweak

**Any other info, error logs, screenshots, ...?**

**Comment by quiprr** [comment]
What device are you on?

**Comment by quiprr** [comment]
Fixed in latest release.
