### ISSUE TITLE
Nothing happens when the server doesn’t respond

### ISSUE THREAD

**Issue by RC-14** [ItHertzSoGood/notiping#2]
Device: iPhone X (GSM)
iOS version: 13.5.1
Jailbreak: OdysseyRa1n

I disabled all tweaks that could possibly be the reason for this (everything that does something to springboard) with iCleaner.

**Comment by quiprr** [comment]
Since this hasn't happened to me or anyone else, I would need to send you a dev build and I would need console logs back. If you're willing to do this let me know.

**Comment by RC-14** [comment]
Installed the update and everything works now.
